### PR TITLE
Make jump tokens configurable

### LINKED ISSUE #1: Use home row keys by default instead of `abc`
This would be IMHO more useful. for touch typists.

### PR DESCRIPTION
**Pull request by globalchubby**
Close #1.

cc: @shelbyd, @hauleth, @rubdos

### CODE REVIEW

**Comment by hauleth** [comment]
I will sell you one neat trick: `git rebase -i`.

After you master that you can go to `git commit --fixup=HEAD` and `git rebase -i --autosquash`

**Comment by globalchubby** [comment]
Why is that better than squash merging? Genuinely curious.

**Comment by hauleth** [comment]
@yangmillstheory for me? Squash will always result with one commit, which isn't always what I want. I prefer small amount of well crafted commits that shows my thought process and evolution of feature.

**Comment by globalchubby** [comment]
Yeah I think if you're careful with commit history it makes sense. My comments are usually unfocused and not descriptive (I don't always feel like doing`git add --patch`, `git commit`, usually just ends up being `"WIP"`), so I tend to want to keep those out of `master`. I could rebase those WIP commits, but then it's more effort. I haven't been converted to this way of committing ~yet~ but I guess I can give it a shot.

**Pull request merged**
